apiVersion: v1
kind: PersistentVolume
metadata:
  name: localdev-sqlpv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/mssql/dbs"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localdev-sqlpv-claim
spec:

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
